#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

ARG sdk_version=1.1.1

FROM digitalasset/daml-sdk:${sdk_version}
WORKDIR /home/sdk
COPY .daml/dist/CdmSwaps-1.0.0.dar /home/sdk/
COPY ui-backend.conf frontend-config.js /home/sdk/

EXPOSE 4000
EXPOSE 6865

CMD ~/.daml/bin/daml sandbox /home/sdk/CdmSwaps-1.0.0.dar & ~/.daml/bin/daml navigator server
