#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

ARG sdk_version=0.13.22

FROM digitalasset/daml-sdk:${sdk_version}

RUN mkdir src
WORKDIR /home/daml/src
COPY daml daml
COPY daml.yaml frontend-config.js ui-backend.conf ./
RUN daml build

EXPOSE 4000

CMD daml navigator server ${LEDGER_HOST} ${LEDGER_PORT}
